""" SISTEM REKOMENDASI BUKU PERPUSTAKAAN """

import time
import random

dataset_buku = {
    ("A"): [
        "Laskar Pelangi - Andrea Hirata",
        "Supernova - Dee Lestari",
        "Bumi Manusia - Pramoedya Ananta Toer",
        "Dilan: Dia adalah Dilanku Tahun 1990 - Pidi Baiq",
        "Orang-Orang Biasa - Andrea Hirata",
        "Ayat-Ayat Cinta - Habiburrahman El Shirazy",
        "Perahu Kertas - Dee Lestari",
        "Kite Runner (Sang Pelari) - Khaled Hosseini",
        "Pulang - Leila S. Chudori",
        "Anak Semua Bangsa - Pramoedya Ananta Toer"
        "Saman - Ayu Utami",
        "Cantik Itu Luka - Eka Kurniawan",
        "Seperti Dendam, Rindu Harus Dibayar Tuntas - Eka Kurniawan",
        "Ronggeng Dukuh Paruk - Ahmad Tohari",
        "Negeri 5 Menara - Ahmad Fuadi",
        "Ranah 3 Warna - Ahmad Fuadi",
        "Rantau 1 Muara - Ahmad Fuadi",
        "Gadis Kretek - Ratih Kumala",
        "Lelaki Harimau - Eka Kurniawan",
        "9 Summers 10 Autumns - Iwan Setyawan",
        "Hujan - Tere Liye",
        "Bumi - Tere Liye",
        "Bulannya - Tere Liye",
        "Pergi - Tere Liye",
        "Tentang Kamu - Tere Liye",
        "Pukat - Tere Liye",
        "Amba - Laksmi Pamuntjak",
        "Aruna dan Lidahnya - Laksmi Pamuntjak",
        "Layangan Putus - Mommy ASF",
        "Rectoverso - Dee Lestari",
        "Filosofi Kopi - Dee Lestari",
        "Rindu - Tere Liye",
        "Hafalan Shalat Delisa - Tere Liye",
        "Aku, Kau dan Sepucuk Angpau Merah - Tere Liye",
        "Manjali dan Cakrabirawa - Ayu Utami",
        "Tarian Bumi - Oka Rusmini",
        "Belenggu - Armijn Pane",
        "Surat Kecil Untuk Tuhan - Agnes Davonar",
        "Cinta di Dalam Gelas - Andrea Hirata",
        "Guru Aini - Andrea Hirata",
        "Tere Liye - Serial Anak Mamak",
        "Kerumunan Terakhir - Okky Madasari",
        "Entrok - Okky Madasari",
        "Maryamah Karpov - Andrea Hirata",
        "Gadis Pantai - Pramoedya Ananta Toer",
        "Titik Nol - Agustinus Wibowo",
        "Kitab Omong Kosong - Seno Gumira Ajidarma",
        "Bidadari-Bidadari Surga - Tere Liye",
        "Sirkus Pohon - Andrea Hirata",
        "Jatuh Cinta Adalah Cara Terbaik Untuk Bunuh Diri - Bernard Batubara",
        "To Kill a Mockingbird - Harper Lee",
        "1984 - George Orwell",
        "Pride and Prejudice - Jane Austen",
        "The Great Gatsby - F. Scott Fitzgerald",
        "Moby Dick - Herman Melville",
        "Wuthering Heights - Emily Brontë",
        "Jane Eyre - Charlotte Brontë",
        "The Catcher in the Rye - J.D. Salinger",
        "The Hobbit - J.R.R. Tolkien",
        "The Lord of the Rings - J.R.R. Tolkien",
        "The Chronicles of Narnia - C.S. Lewis",
        "Harry Potter and the Sorcerer's Stone - J.K. Rowling",
        "Harry Potter and the Chamber of Secrets - J.K. Rowling",
        "The Hunger Games - Suzanne Collins",
        "Catching Fire - Suzanne Collins",
        "Mockingjay - Suzanne Collins",
        "The Maze Runner - James Dashner",
        "The Scorch Trials - James Dashner",
        "Divergent - Veronica Roth",
        "Insurgent - Veronica Roth",
        "Allegiant - Veronica Roth",
        "Twilight - Stephenie Meyer",
        "New Moon - Stephenie Meyer",
        "Eclipse - Stephenie Meyer",
        "Breaking Dawn - Stephenie Meyer",
        "The Fault in Our Stars - John Green",
        "Looking for Alaska - John Green",
        "Paper Towns - John Green",
        "An Abundance of Katherines - John Green",
        "The Perks of Being a Wallflower - Stephen Chbosky",
        "A Game of Thrones - George R.R. Martin",
        "A Clash of Kings - George R.R. Martin",
        "A Storm of Swords - George R.R. Martin",
        "A Feast for Crows - George R.R. Martin",
        "A Dance with Dragons - George R.R. Martin",
        "The Book Thief - Markus Zusak",
        "The Night Circus - Erin Morgenstern",
        "Life of Pi - Yann Martel",
        "The Alchemist - Paulo Coelho",
        "The Shadow of the Wind - Carlos Ruiz Zafón",
        "The Kite Runner - Khaled Hosseini",
        "A Thousand Splendid Suns - Khaled Hosseini",
        "And the Mountains Echoed - Khaled Hosseini",
        "The Giver - Lois Lowry",
        "The Outsiders - S.E. Hinton",
        "Frankenstein - Mary Shelley",
        "Dracula - Bram Stoker",
        "The Picture of Dorian Gray - Oscar Wilde",
        "Brave New World - Aldous Huxley"
    ],
    ("B"): [
        "Manusia Setengah Salmon - Raditya Dika",
        "Catatan Juang - Fiersa Besari",
        "Sapiens: Riwayat Singkat Umat Manusia - Yuval Noah Harari",
        "Filosofi Kopi - Dee Lestari",
        "The Subtle Art of Not Giving a F*ck - Mark Manson",
        "Di Tanah Lada - Ziggy Z.",
        "Melawan Takdir - Gus Dur",
        "Habibie & Ainun - Bacharuddin Jusuf Habibie",
        "Narasi Semesta - Fiersa Besari",
        "Kisah Tanah Jawa: Horor Nusantara - Bonaventura Genta"
                "Pulang - Tere Liye",
        "Negeri Para Bedebah - Tere Liye",
        "Ronggeng Dukuh Paruk - Ahmad Tohari",
        "Laut Bercerita - Leila S. Chudori",
        "Orang-Orang Proyek - Ahmad Tohari",
        "Bumi Manusia - Pramoedya Ananta Toer",
        "Anak Semua Bangsa - Pramoedya Ananta Toer",
        "Jejak Langkah - Pramoedya Ananta Toer",
        "Rumah Kaca - Pramoedya Ananta Toer",
        "Aku Ingin Cerita Kepadamu - Sapardi Djoko Damono",
        "Gadis Kretek - Ratih Kumala",
        "9 Summers 10 Autumns - Iwan Setyawan",
        "Perahu Kertas - Dee Lestari",
        "Rectoverso - Dee Lestari",
        "Mimpi Sejuta Dolar - Merry Riana",
        "Laskar Pelangi - Andrea Hirata",
        "Sang Pemimpi - Andrea Hirata",
        "Edensor - Andrea Hirata",
        "Maryamah Karpov - Andrea Hirata",
        "Cinta Dalam Gelas - Andrea Hirata",
        "Tuhan Izinkan Aku Menjadi Pelacur - Muhidin M. Dahlan",
        "Kitab Omong Kosong - Seno Gumira Ajidarma",
        "Dilan 1990 - Pidi Baiq",
        "Dilan 1991 - Pidi Baiq",
        "Milea: Suara Dari Dilan - Pidi Baiq",
        "Galaksi Kinanthi - Tasaro GK",
        "Cinta Tak Pernah Tepat Waktu - Puthut EA",
        "Tentang Kamu - Tere Liye",
        "Ayah - Andrea Hirata",
        "Surat Kecil Untuk Tuhan - Agnes Davonar",
        "Rindu - Tere Liye",
        "Bidadari-Bidadari Surga - Tere Liye",
        "Daun Yang Jatuh Tak Pernah Membenci Angin - Tere Liye",
        "Hujan - Tere Liye",
                "Educated - Tara Westover",
        "Becoming - Michelle Obama",
        "Thinking, Fast and Slow - Daniel Kahneman",
        "The Power of Habit - Charles Duhigg",
        "Outliers: The Story of Success - Malcolm Gladwell",
        "Atomic Habits - James Clear",
        "Grit: The Power of Passion and Perseverance - Angela Duckworth",
        "Man's Search for Meaning - Viktor E. Frankl",
        "Quiet: The Power of Introverts in a World That Can't Stop Talking - Susan Cain",
        "The 7 Habits of Highly Effective People - Stephen R. Covey",
        "The Alchemist - Paulo Coelho",
        "The Four Agreements - Don Miguel Ruiz",
        "Why We Sleep - Matthew Walker",
        "How to Win Friends and Influence People - Dale Carnegie",
        "The Lean Startup - Eric Ries",
        "Start with Why - Simon Sinek",
        "Drive: The Surprising Truth About What Motivates Us - Daniel H. Pink",
        "Freakonomics - Steven D. Levitt and Stephen J. Dubner",
        "SuperFreakonomics - Steven D. Levitt and Stephen J. Dubner",
        "The Tipping Point - Malcolm Gladwell",
        "Blink: The Power of Thinking Without Thinking - Malcolm Gladwell",
        "Dare to Lead - Brené Brown",
        "Rising Strong - Brené Brown",
        "The Gifts of Imperfection - Brené Brown",
        "12 Rules for Life - Jordan B. Peterson",
        "Beyond Order - Jordan B. Peterson",
        "Shoe Dog: A Memoir by the Creator of Nike - Phil Knight",
        "Tools of Titans - Tim Ferriss",
        "The 5 AM Club - Robin Sharma",
        "The Monk Who Sold His Ferrari - Robin Sharma",
        "Deep Work - Cal Newport",
        "So Good They Can't Ignore You - Cal Newport",
        "Digital Minimalism - Cal Newport",
        "Mindset: The New Psychology of Success - Carol S. Dweck",
        "Extreme Ownership - Jocko Willink",
        "Leaders Eat Last - Simon Sinek",
        "The Obstacle Is the Way - Ryan Holiday",
        "Ego Is the Enemy - Ryan Holiday",
        "Stillness Is the Key - Ryan Holiday",
        "Meditations - Marcus Aurelius",
        "Antifragile: Things That Gain from Disorder - Nassim Nicholas Taleb",
        "The Black Swan - Nassim Nicholas Taleb",
        "Fooled by Randomness - Nassim Nicholas Taleb",
        "The Big Short - Michael Lewis",
        "Flash Boys - Michael Lewis",
        "Thinking in Bets - Annie Duke",
        "The Hard Thing About Hard Things - Ben Horowitz",
        "Principles: Life and Work - Ray Dalio",
        "Measure What Matters - John Doerr",
        "The Art of War - Sun Tzu"
    ],
    ("C"): [
        "Saga of the Seven Suns - Kevin J. Anderson",
        "Hitchhiker’s Guide to the Galaxy - Douglas Adams",
        "The Martian - Andy Weir",
        "Neuromancer - William Gibson",
        "Ender’s Game - Orson Scott Card",
        "Dune - Frank Herbert",
        "1984 - George Orwell",
        "Fahrenheit 451 - Ray Bradbury",
        "Anathem - Neal Stephenson",
        "Angkasa dan Kemenangan - Asma Nadia"
        "Bumi - Tere Liye",
        "Bulan - Tere Liye",
        "Matahari - Tere Liye",
        "Ceros dan Batozar - Tere Liye",
        "Nebula - Tere Liye",
        "Selena - Tere Liye",
        "Laut Bercerita - Leila S. Chudori",
        "Mantra Asmara - Rintik Sedu",
        "Republik Alternatif - Okky Madasari",
        "Noktah Merah di Bibir Laut - Arafat Nur",
        "Kitab Omong Kosong - Seno Gumira Ajidarma",
        "Rahasia Langit - Dewi Lestari",
        "Partikel - Dewi Lestari",
        "Supernova - Dewi Lestari",
        "Perahu Kertas - Dewi Lestari",
        "Kepingan Antariksa - Haidar Musyafa",
        "Teka-Teki Masa Depan - Sapardi Djoko Damono",
        "Di Ujung Cahaya - Nuril Basri",
        "Ruang Waktu - Titi Sanaria",
        "Kehilangan Bintang - Felix Siauw",
        "Penantian Terakhir - Ahmad Tohari",
        "Di Balik Lorong Waktu - Risa Saraswati",
        "Laskar Pelangi - Andrea Hirata",
        "Pulang - Leila S. Chudori",
        "Aksara Bintang - J.S. Khairen",
        "Purnama di Langit - Pramoedya Ananta Toer",
        "Arus Balik - Pramoedya Ananta Toer",
        "Waktu Tanpa Batas - Okky Madasari",
        "Hujan - Tere Liye",
        "Komet - Tere Liye",
        "Komet Minor - Tere Liye",
        "Petualangan Futura - Reda Gaudiamo",
        "Menuju Planet Asing - N.H. Dini",
        "Bintang yang Jatuh - Widji Thukul",
        "Langit dan Lautan - Clara Ng",
        "Mimpi Tanpa Batas - Siska Nurul Hidayah",
        "Labirin Waktu - Rosi L. Simamora",
        "Sepenggal Antariksa - S.M. Zaki",
        "Langkah Menembus Waktu - Eka Kurniawan",
        "Api di Langit Senja - A. Fuadi",
        "Brave New World - Aldous Huxley",
        "Foundation - Isaac Asimov",
        "I, Robot - Isaac Asimov",
        "The Left Hand of Darkness - Ursula K. Le Guin",
        "Snow Crash - Neal Stephenson",
        "Hyperion - Dan Simmons",
        "The Forever War - Joe Haldeman",
        "Stranger in a Strange Land - Robert A. Heinlein",
        "Rendezvous with Rama - Arthur C. Clarke",
        "2001: A Space Odyssey - Arthur C. Clarke",
        "Childhood's End - Arthur C. Clarke",
        "The Time Machine - H.G. Wells",
        "The War of the Worlds - H.G. Wells",
        "The Invisible Man - H.G. Wells",
        "The Moon is a Harsh Mistress - Robert A. Heinlein",
        "Do Androids Dream of Electric Sheep? - Philip K. Dick",
        "Ubik - Philip K. Dick",
        "The Man in the High Castle - Philip K. Dick",
        "Altered Carbon - Richard K. Morgan",
        "The Expanse: Leviathan Wakes - James S.A. Corey",
        "Red Mars - Kim Stanley Robinson",
        "Blue Mars - Kim Stanley Robinson",
        "Green Mars - Kim Stanley Robinson",
        "Perdido Street Station - China Miéville",
        "The Scar - China Miéville",
        "The City & the City - China Miéville",
        "Starship Troopers - Robert A. Heinlein",
        "Old Man’s War - John Scalzi",
        "The Last Colony - John Scalzi",
        "Spin - Robert Charles Wilson",
        "Blind Lake - Robert Charles Wilson",
        "The Diamond Age - Neal Stephenson",
        "Seveneves - Neal Stephenson",
        "Annihilation - Jeff VanderMeer",
        "Authority - Jeff VanderMeer",
        "Acceptance - Jeff VanderMeer",
        "The Three-Body Problem - Liu Cixin",
        "The Dark Forest - Liu Cixin",
        "Death's End - Liu Cixin",
        "The Space Between Worlds - Micaiah Johnson",
        "Station Eleven - Emily St. John Mandel",
        "The Road - Cormac McCarthy",
        "Dark Matter - Blake Crouch",
        "Recursion - Blake Crouch",
        "Cloud Atlas - David Mitchell",
        "The Book of Strange New Things - Michel Faber",
        "Solaris - Stanislaw Lem",
        "The Dispossessed - Ursula K. Le Guin",
        "Kindred - Octavia E. Butler",
        "Parable of the Sower - Octavia E. Butler",
        "Oryx and Crake - Margaret Atwood",
        "The Handmaid's Tale - Margaret Atwood"
    ],
    ("D"): [
        "Harry Potter dan Batu Bertuah - J.K. Rowling",
        "The Hobbit - J.R.R. Tolkien",
        "Percy Jackson: Pencuri Petir - Rick Riordan",
        "The Lord of the Rings - J.R.R. Tolkien",
        "Game of Thrones - George R.R. Martin",
        "Artemis Fowl - Eoin Colfer",
        "Narnia: Sang Singa, Sang Penyihir, dan Lemari - C.S. Lewis",
        "Negeri Para Bedebah - Tere Liye",
        "Legenda Naga: Dwilogi Dragonian - Sanie B. Kuncoro",
        "Hujan - Tere Liye"
                "Bumi - Tere Liye",
        "Bulan - Tere Liye",
        "Matahari - Tere Liye",
        "Bintang - Tere Liye",
        "Ceros dan Batozar - Tere Liye",
        "Komet - Tere Liye",
        "Komet Minor - Tere Liye",
        "Selena - Tere Liye",
        "Nebula - Tere Liye",
        "Si Putih - Tere Liye",
        "Dwilogi Padang Bulan - Andrea Hirata",
        "Laskar Pelangi - Andrea Hirata",
        "Sunset Bersama Rosie - Tere Liye",
        "Rahasia Hujan - Haqi Achmad",
        "Purnama di Negeri Naga - S. Mara Gd",
        "Seri Petualangan Anak - Djokolelono",
        "Thalita - Maya Lestari Gf",
        "Ratu dan Raden - Eliza Vitri Handayani",
        "Legenda Putri Ong Tien - Fanny J. Poyk",
        "Anak Rembulan - Arleen A."
        "Saga: Cerita Anak Bumi - Okky Madasari",
        "Pasung Jiwa - Okky Madasari",
        "Supernova: Ksatria, Puteri, dan Bintang Jatuh - Dee Lestari",
        "Supernova: Gelombang - Dee Lestari",
        "Supernova: Akar - Dee Lestari",
        "Tarian Bumi - Oka Rusmini",
        "Kisah dari Negeri Fantasi - Dian Purnomo",
        "Lelang Surga - Dewi Ria Utari",
        "Gerbang Nuswantara - Valiant Budi",
        "Naga Bumi - S. Mara Gd",
        "Anak Penangkap Hantu - Dwi Ratih Ramadhan",
        "Legenda Asli Jawa - Ratna Indraswari Ibrahim",
        "Kembara Rindu - Habiburrahman El Shirazy",
        "Misteri di Balik Pintu - Clara Ng",
        "Kota Para Rahasia - Martha Heidy",
        "Sejarah Naga Merah - Ardy Kresna C",
        "Merindu Cahaya de Amstel - Arumi E",
        "Putri Hujan dan Ksatria Malam - Djokolelono",
        "Para Penyihir dari Banten - Wayan Sunarta",
        "Istana di Atas Awan - Christian Simamora",
                "Eragon - Christopher Paolini",
        "Eldest - Christopher Paolini",
        "Brisingr - Christopher Paolini",
        "Inheritance - Christopher Paolini",
        "Mistborn: The Final Empire - Brandon Sanderson",
        "The Well of Ascension - Brandon Sanderson",
        "The Hero of Ages - Brandon Sanderson",
        "Warbreaker - Brandon Sanderson",
        "Elantris - Brandon Sanderson",
        "The Way of Kings - Brandon Sanderson",
        "Words of Radiance - Brandon Sanderson",
        "Oathbringer - Brandon Sanderson",
        "Rhythm of War - Brandon Sanderson",
        "The Name of the Wind - Patrick Rothfuss",
        "The Wise Man's Fear - Patrick Rothfuss",
        "The Slow Regard of Silent Things - Patrick Rothfuss",
        "Shadow and Bone - Leigh Bardugo",
        "Siege and Storm - Leigh Bardugo",
        "Ruin and Rising - Leigh Bardugo",
        "Six of Crows - Leigh Bardugo",
        "Crooked Kingdom - Leigh Bardugo",
        "The Night Circus - Erin Morgenstern",
        "Caraval - Stephanie Garber",
        "Legendary - Stephanie Garber",
        "Finale - Stephanie Garber",
        "Throne of Glass - Sarah J. Maas",
        "Crown of Midnight - Sarah J. Maas",
        "Heir of Fire - Sarah J. Maas",
        "Queen of Shadows - Sarah J. Maas",
        "Empire of Storms - Sarah J. Maas",
        "Kingdom of Ash - Sarah J. Maas",
        "A Court of Thorns and Roses - Sarah J. Maas",
        "A Court of Mist and Fury - Sarah J. Maas",
        "A Court of Wings and Ruin - Sarah J. Maas",
        "The Cruel Prince - Holly Black",
        "The Wicked King - Holly Black",
        "The Queen of Nothing - Holly Black",
        "Stardust - Neil Gaiman",
        "Coraline - Neil Gaiman",
        "Neverwhere - Neil Gaiman",
        "American Gods - Neil Gaiman",
        "Good Omens - Neil Gaiman & Terry Pratchett",
        "The Graveyard Book - Neil Gaiman",
        "Anansi Boys - Neil Gaiman",
        "The Golden Compass - Philip Pullman",
        "The Subtle Knife - Philip Pullman",
        "The Amber Spyglass - Philip Pullman",
        "Howl's Moving Castle - Diana Wynne Jones",
        "Castle in the Air - Diana Wynne Jones",
        "House of Many Ways - Diana Wynne Jones"
    ],
    ("E"): [
        "Ayat-Ayat Cinta - Habiburrahman El Shirazy",
        "Ketika Cinta Bertasbih - Habiburrahman El Shirazy",
        "Dilan: Dia Adalah Dilanku Tahun 1990 - Pidi Baiq",
        "Perahu Kertas - Dee Lestari",
        "Rindu - Tere Liye",
        "Hujan Bulan Juni - Sapardi Djoko Damono",
        "Rectoverso - Dee Lestari",
        "Critical Eleven - Ika Natassa",
        "Twilight - Stephenie Meyer",
        "Loving a Vampire - William R."
        "Cinta Itu Buta - Clara Ng",
        "Seperti Dendam, Rindu Harus Dibayar Tuntas - Eka Kurniawan",
        "Mengejar Matahari - Tere Liye",
        "The Naked Traveler 7 - Trinity",
        "Bulan - Tere Liye",
        "Matahari - Tere Liye",
        "Cinta Tak Pernah Salah - Lilik Dwi R. S.",
        "Jejak Langkah - Ahmad Tohari",
        "Langit Tak Menangis - Husein M. S.",
        "Kucinta Kamu - Riawani Elyta",
        "Kembali Cinta - Fauzia N. S.",
        "Boleh Jadi Cinta - Windy Puspitadewi",
        "Cinta di Dalam Hati - Habiburrahman El Shirazy",
        "Kau, Aku, dan Sepucuk Angpau Merah - Sitta Karina",
        "Menunggu Cinta - Rina Suryakusuma",
        "Bintang di Langit Biru - Evi C. S.",
        "Malam Tak Berujung - Diana Rikasari",
        "Lelaki Terhebat - Sinta Yudisia",
        "Sepucuk Cinta - Zhaenal Abidin",
        "Cinta di Kamar Mandi - Tia Smania",
        "Dua Cinta - Fida A. K.",
        "Cinta Sejati Adalah - Shendy Hermawan",
        "Tuhan Cinta, Aku Cinta Kamu - Luluk Hidayati",
        "Jatuh Cinta - Ratih Kumala",
        "Menjadi Cinta - Dian L. S.",
        "Cinta dalam Hati - Lidyawati Dwi Pratiwi",
        "Lalu Cinta Pun Datang - Aulia A. T.",
        "Merindu Cinta - Eka S. C.",
        "Berkisah Cinta - Donny D. W.",
        "Satu Cinta, Satu Hati - Fatima A. Z.",
        "Ku Cinta Kamu - Lia Setiawati",
        "Cinta Terindah - Zulfikar D. A.",
        "Mengenal Cinta - Nadia K.",
        "Rindu dalam Senyuman - Ayi W. C.",
        "Bila Cinta - Evi P. W.",
        "Jangan Pernah Lupa Cinta - Fitri D. A.",
        "Satu Malam Cinta - Melisa N.",
        "Cinta Itu Sederhana - Andika S.",
        "Hati Cinta - Dina S. K.",
        "Waktu Cinta - Theresia L.",
        "Pride and Prejudice - Jane Austen",
        "Sense and Sensibility - Jane Austen",
        "Emma - Jane Austen",
        "Wuthering Heights - Emily Bronte",
        "Jane Eyre - Charlotte Bronte",
        "The Notebook - Nicholas Sparks",
        "A Walk to Remember - Nicholas Sparks",
        "Dear John - Nicholas Sparks",
        "Safe Haven - Nicholas Sparks",
        "Me Before You - Jojo Moyes",
        "After You - Jojo Moyes",
        "Still Me - Jojo Moyes",
        "The Fault in Our Stars - John Green",
        "Looking for Alaska - John Green",
        "Paper Towns - John Green",
        "To All the Boys I've Loved Before - Jenny Han",
        "P.S. I Still Love You - Jenny Han",
        "Always and Forever, Lara Jean - Jenny Han",
        "Eleanor & Park - Rainbow Rowell",
        "Fangirl - Rainbow Rowell",
        "Attachments - Rainbow Rowell",
        "Anna and the French Kiss - Stephanie Perkins",
        "Lola and the Boy Next Door - Stephanie Perkins",
        "Isla and the Happily Ever After - Stephanie Perkins",
        "Love & Gelato - Jenna Evans Welch",
        "Love & Luck - Jenna Evans Welch",
        "Love & Olives - Jenna Evans Welch",
        "The Summer I Turned Pretty - Jenny Han",
        "It's Not Summer Without You - Jenny Han",
        "We'll Always Have Summer - Jenny Han",
        "Twilight - Stephenie Meyer",
        "New Moon - Stephenie Meyer",
        "Eclipse - Stephenie Meyer",
        "Breaking Dawn - Stephenie Meyer",
        "Midnight Sun - Stephenie Meyer",
        "The Selection - Kiera Cass",
        "The Elite - Kiera Cass",
        "The One - Kiera Cass",
        "The Heir - Kiera Cass",
        "The Crown - Kiera Cass",
        "Beautiful Disaster - Jamie McGuire",
        "Walking Disaster - Jamie McGuire",
        "The Rosie Project - Graeme Simsion",
        "The Rosie Effect - Graeme Simsion",
        "Every Breath - Nicholas Sparks",
        "Every Breath You Take - Mary Higgins Clark",
        "It Ends With Us - Colleen Hoover",
        "Ugly Love - Colleen Hoover",
        "Verity - Colleen Hoover",
        "Confess - Colleen Hoover",
        "November 9 - Colleen Hoover",
    ],
    ("F"): [
        "Sherlock Holmes: A Study in Scarlet - Arthur Conan Doyle",
        "Murder on the Orient Express - Agatha Christie",
        "And Then There Were None - Agatha Christie",
        "The Girl with the Dragon Tattoo - Stieg Larsson",
        "The Da Vinci Code - Dan Brown",
        "Perempuan Berkalung Sorban - Abidah El Khalieqy",
        "Negeri 5 Menara - Ahmad Fuadi",
        "Gadis Kretek - Ratih Kumala",
        "Kasus Misterius Drupadi - Seno Gumira Ajidarma",
        "Rahasia Meede - E.S. Ito"
        "Teka-Teki Terakhir - S. Mara Gd",
        "Hujan Bulan Juni - Sapardi Djoko Damono",
        "Lelaki Harimau - Eka Kurniawan",
        "Cantik Itu Luka - Eka Kurniawan",
        "Dua Belas Pasang Mata - Doddy Pribadi",
        "Detektif Kecil Tsubasa - Yudhistira Massardi",
        "Para Priyayi - Umar Kayam",
        "Bunga-Bunga yang Jatuh - Mochtar Lubis",
        "Si Jago Merah - Abdullah Harahap",
        "Balada Si Roy - Gol A Gong",
        "Burung-Burung Manyar - Y.B. Mangunwijaya",
        "Kejahatan di Kali Duren - S. Mara Gd",
        "The Architecture of Love - Ika Natassa",
        "Pulang - Leila S. Chudori",
        "Amba - Laksmi Pamuntjak",
        "Namaku Hiroko - Nh. Dini",
        "Harta Haram Jadah - Tere Liye",
        "Bidadari-Bidadari Surga - Tere Liye",
        "Seruni - Mira W.",
        "Jejak Langkah - Pramoedya Ananta Toer",
        "Rumah Kaca - Pramoedya Ananta Toer",
        "Panggilan Rasul - Abidah El Khalieqy",
        "Surat Kecil untuk Tuhan - Agnes Davonar",
        "Dua Garis Biru - Lucia Priandarini",
        "Si Buta dari Gua Hantu - Ganes Th",
        "Sang Pemimpi - Andrea Hirata",
        "Laskar Pelangi - Andrea Hirata",
        "Ayah - Andrea Hirata",
        "Guru Aini - Andrea Hirata",
        "Gadis Pantai - Pramoedya Ananta Toer",
        "Kalung Kematian - Abdullah Harahap",
        "Misteri Kota Tua - Ruwi Meita",
        "Pembunuhan di Jalan Pintu Besar - Yudhistira Massardi",
        "Saksi Mata - Seno Gumira Ajidarma",
        "Ronggeng Dukuh Paruk - Ahmad Tohari",
        "Lintang Kemukus - Ahmad Tohari",
        "Belantik - Ahmad Tohari",
        "Mantra Pejinak Ular - Kurnia Effendi",
        "Surat Dahlan - Khrisna Pabichara",
        "Detektif Ikan Mas - Djokolelono",
        "The Hound of the Baskervilles - Arthur Conan Doyle",
        "The Adventures of Sherlock Holmes - Arthur Conan Doyle",
        "The Sign of the Four - Arthur Conan Doyle",
        "A Study in Scarlet - Arthur Conan Doyle",
        "The Secret Adversary - Agatha Christie",
        "Death on the Nile - Agatha Christie",
        "The ABC Murders - Agatha Christie",
        "The Murder of Roger Ackroyd - Agatha Christie",
        "The Mystery of the Blue Train - Agatha Christie",
        "The Moonstone - Wilkie Collins",
        "The Woman in White - Wilkie Collins",
        "The Big Sleep - Raymond Chandler",
        "Farewell, My Lovely - Raymond Chandler",
        "The Maltese Falcon - Dashiell Hammett",
        "The Thin Man - Dashiell Hammett",
        "In the Woods - Tana French",
        "The Likeness - Tana French",
        "Gone Girl - Gillian Flynn",
        "Dark Places - Gillian Flynn",
        "Sharp Objects - Gillian Flynn",
        "The Cuckoo's Calling - Robert Galbraith",
        "The Silkworm - Robert Galbraith",
        "Career of Evil - Robert Galbraith",
        "The Girl on the Train - Paula Hawkins",
        "Into the Water - Paula Hawkins",
        "Big Little Lies - Liane Moriarty",
        "Nine Perfect Strangers - Liane Moriarty",
        "The Shadow of the Wind - Carlos Ruiz Zafón",
        "The Angel's Game - Carlos Ruiz Zafón",
        "The Prisoner of Heaven - Carlos Ruiz Zafón",
        "The Labyrinth of the Spirits - Carlos Ruiz Zafón",
        "Before I Go to Sleep - S.J. Watson",
        "The Reversal - Michael Connelly",
        "The Lincoln Lawyer - Michael Connelly",
        "Blood Work - Michael Connelly",
        "The Black Echo - Michael Connelly",
        "The Poet - Michael Connelly",
        "Still Life - Louise Penny",
        "A Fatal Grace - Louise Penny",
        "The Cruelest Month - Louise Penny",
        "The Dry - Jane Harper",
        "Force of Nature - Jane Harper",
        "The Lost Man - Jane Harper",
        "The Girl Who Played with Fire - Stieg Larsson",
        "The Girl Who Kicked the Hornet's Nest - Stieg Larsson",
        "The Girl in the Spider's Web - David Lagercrantz",
        "The Girl Who Takes an Eye for an Eye - David Lagercrantz",
        "The Alienist - Caleb Carr",
        "Angel of Darkness - Caleb Carr"        
    ],
    ("G"): [
        "Inferno - Dan Brown",
        "Gone Girl - Gillian Flynn",
        "The Silent Patient - Alex Michaelides",
        "Sharp Objects - Gillian Flynn",
        "The Couple Next Door - Shari Lapena",
        "Orang Asing di Dekat Rumah - Shari Lapena",
        "The Girl on the Train - Paula Hawkins",
        "Dark Places - Gillian Flynn",
        "Pengkhianatan Tanpa Jejak - Ian Rankin",
        "Nyanyian Akar Rumput - Wiji Thukul"
        "Matahari di Balik Daun - Mira W",
        "Saksi Mata - S Mara Gd",
        "Rahasia Pelangi - S Mara Gd",
        "Anak Rembulan - Tere Liye",
        "Negeri Para Bedebah - Tere Liye",
        "Kejora di Langit Jakarta - Mira W",
        "Perang Terakhir - Tere Liye",
        "Rahasia Hujan - S Mara Gd",
        "Rumah Berhantu di Ujung Jalan - Clara Ng",
        "Darah dan Mahkota - Fiersa Besari",
        "Jejak Liar - Mira W",
        "Kupu-Kupu Malam - Mira W",
        "Cermin Retak - Mira W",
        "Luka Tanah Air - Risa Saraswati",
        "Setengah Jalan Menuju Gelap - Bernard Batubara",
        "Sepasang Kekasih di Ujung Jalan - Clara Ng",
        "Hilangnya Senja - S Mara Gd",
        "Rahasia Gua Beracun - S Mara Gd",
        "Gerbang Pengetahuan Terlarang - Ary Nilandari",
        "Kembang Kematian - Arswendo Atmowiloto",
        "Pintu Terakhir - Mira W",
        "Lukisan Kematian - Risa Saraswati",
        "Senyap di Dalam Angin - Eka Kurniawan",
        "Kota Tanpa Nama - Eka Kurniawan",
        "Anatomi Rasa Takut - Fira Basuki",
        "Jejak Mayat - Mira W",
        "Pelangi yang Retak - S Mara Gd",
        "Rumah Hantu Penari - Clara Ng",
        "Dendam Tak Berkesudahan - Mira W",
        "Senja di Balik Kabut - Mira W",
        "Kebakaran Tengah Malam - Mira W",
        "Rahasia Pulau Terlarang - S Mara Gd",
        "Sepucuk Surat dari Masa Lalu - Bernard Batubara",
        "Hujan Merah Darah - Mira W",
        "Laut Tak Bertepi - Fira Basuki",
        "Perempuan di Balik Jendela - Mira W",
        "Rahasia Kebun Hitam - S Mara Gd",
        "Kisah Gelap di Ujung Lorong - Clara Ng",
        "Jejak Tak Kasat Mata - Risa Saraswati",
        "Misteri Rumah Kaca - Mira W",
        "The Girl with the Dragon Tattoo - Stieg Larsson",
        "Before I Go to Sleep - S.J. Watson",
        "Big Little Lies - Liane Moriarty",
        "In the Woods - Tana French",
        "The Widow - Fiona Barton",
        "Behind Closed Doors - B.A. Paris",
        "The Da Vinci Code - Dan Brown",
        "Angels & Demons - Dan Brown",
        "Shutter Island - Dennis Lehane",
        "The Chain - Adrian McKinty",
        "The Woman in Cabin 10 - Ruth Ware",
        "The Hunting Party - Lucy Foley",
        "The Guest List - Lucy Foley",
        "No Exit - Taylor Adams",
        "Verity - Colleen Hoover",
        "Lock Every Door - Riley Sager",
        "Home Before Dark - Riley Sager",
        "The Last Time I Lied - Riley Sager",
        "Final Girls - Riley Sager",
        "The Escape Room - Megan Goldin",
        "An Anonymous Girl - Greer Hendricks",
        "The Wife Between Us - Greer Hendricks",
        "The Perfect Nanny - Leila Slimani",
        "The Kind Worth Killing - Peter Swanson",
        "The Silent Corner - Dean Koontz",
        "Intensity - Dean Koontz",
        "The Outsider - Stephen King",
        "Mr. Mercedes - Stephen King",
        "Finders Keepers - Stephen King",
        "End of Watch - Stephen King",
        "Misery - Stephen King",
        "The Shining - Stephen King",
        "Doctor Sleep - Stephen King",
        "Gone Tomorrow - Lee Child",
        "Killing Floor - Lee Child",
        "Bad Luck and Trouble - Lee Child",
        "The Reversal - Michael Connelly",
        "The Black Echo - Michael Connelly",
        "The Girl Beneath the Sea - Andrew Mayne",
        "The Stranger Diaries - Elly Griffiths",
        "The Shadow of the Wind - Carlos Ruiz Zafon",
        "Her Every Fear - Peter Swanson",
        "The Good Girl - Mary Kubica",
        "Pretty Girls - Karin Slaughter",
        "Triptych - Karin Slaughter",
        "The Kept Woman - Karin Slaughter",
        "The Passenger - Lisa Lutz",
        "All the Missing Girls - Megan Miranda",
        "The Last House on Needless Street - Catriona Ward",
        "The Turn of the Key - Ruth Ware"
    ],
    ("H"): [
        "Danur - Risa Saraswati",
        "Maddah - Risa Saraswati",
        "Sebelum Iblis Menjemput - Risa Saraswati",
        "KKN di Desa Penari - Simpleman",
        "Horor Nusantara - Kisah Tanah Jawa",
        "Goosebumps - R.L. Stine",
        "It - Stephen King",
        "Pet Sematary - Stephen King",
        "Dollhouse - Anindita S. Thayf",
        "The Haunting of Hill House - Shirley Jackson"
        "Sundel Bolong - Leila S. Chudori",
        "Gerbang Dialog Danur - Risa Saraswati",
        "Pulang - Tere Liye",
        "Lukisan Kaligrafi - Fajar A. S. D. ",
        "Jurnal Risa - Risa Saraswati",
        "Sebelas Patriot - Andrea Hirata",
        "Lantai 13 - Ruwi Meita",
        "Rumah di Seribu Ombak - Erwin Arnada",
        "Garis Waktu - Fiersa Besari",
        "Hantu Rumah Tua - Putri Aprilia",
        "Bayangan Ratu Adil - Moammar Emka",
        "Cermin Retak - Clara Ng",
        "Tarian Setan - Fajar A. S. D.",
        "Rumah Kentang - Bonaventura Genta",
        "Teror Kota Lama - Wening Dwiari",
        "Kisah Nyata dari Bawah - Fitri Sari",
        "Jangan Menoleh - Agatha Sandi",
        "Sampai Jumpa di Surga - Ruwi Meita",
        "Selama Kamu Hidup - Fitri Tropica",
        "Pusaka - Arief Rahmat",
        "Kuburan Hantu - Zainuddin A. S.",
        "Legenda Misteri Gunung Salak - Risa Saraswati",
        "Tembang Lingsir - Dani Rendra",
        "Kuntilanak di Balik Jendela - Ningsih",
        "Misteri Hantu Kampung - Genta",
        "Beringin Tua - Eka Kurniawan",
        "Horor Lintas Negara - Nanda Fitriana",
        "Rumah Belanda - Anindita S. Thayf",
        "Gentayangan - Intan Paramaditha",
        "Tiga Malam di Stasiun Kereta - Aulia Fajrin",
        "Sekolah Angker - Dani Rendra",
        "Ruang Gelap - Eka Kurniawan",
        "Suster Gepeng - Arief Rahmat",
        "Janur Kuning Berdarah - Setyaningsih",
        "Kisah Pojok Ruangan - Fajar Meita",
        "Hantu Kamar Kos - Yuniar",
        "Kuburan Dalam Mimpi - Anis Fitriani",
        "Tali Pocong Perawan - Bonaventura Genta",
        "Iblis dalam Cermin - Clara Ng",
        "Pintu Ke Alam Gaib - Wening Dwiari",
        "Dracula - Bram Stoker",
        "Frankenstein - Mary Shelley",
        "The Shining - Stephen King",
        "Misery - Stephen King",
        "Salem's Lot - Stephen King",
        "Carrie - Stephen King",
        "The Exorcist - William Peter Blatty",
        "Hell House - Richard Matheson",
        "Bird Box - Josh Malerman",
        "Mexican Gothic - Silvia Moreno-Garcia",
        "The Woman in Black - Susan Hill",
        "The Turn of the Screw - Henry James",
        "House of Leaves - Mark Z. Danielewski",
        "Coraline - Neil Gaiman",
        "The Graveyard Book - Neil Gaiman",
        "The Silence of the Lambs - Thomas Harris",
        "The Girl with All the Gifts - M.R. Carey",
        "The Outsider - Stephen King",
        "NOS4A2 - Joe Hill",
        "Locke & Key - Joe Hill",
        "The Amityville Horror - Jay Anson",
        "The Little Stranger - Sarah Waters",
        "The Terror - Dan Simmons",
        "The Ruins - Scott Smith",
        "Ghost Story - Peter Straub",
        "Haunted - Chuck Palahniuk",
        "Something Wicked This Way Comes - Ray Bradbury",
        "The Fisherman - John Langan",
        "The Troop - Nick Cutter",
        "The Deep - Nick Cutter",
        "The Changeling - Victor LaValle",
        "Carmilla - Sheridan Le Fanu",
        "The Doll Factory - Elizabeth Macneal",
        "We Have Always Lived in the Castle - Shirley Jackson",
        "Let the Right One In - John Ajvide Lindqvist",
        "The Ritual - Adam Nevill",
        "The Dark - James Herbert",
        "The Taking - Dean Koontz",
        "Phantoms - Dean Koontz",
        "The Black Phone - Joe Hill",
        "Cold Moon Over Babylon - Michael McDowell",
        "The Elementals - Michael McDowell",
        "The Mist - Stephen King",
        "The Grownup - Gillian Flynn",
        "I Am Legend - Richard Matheson",
        "The Shadow Over Innsmouth - H.P. Lovecraft",
        "At the Mountains of Madness - H.P. Lovecraft",
        "The Call of Cthulhu - H.P. Lovecraft",
        "The Lovecraft Compendium - H.P. Lovecraft",
        "World War Z - Max Brooks",
        "Revival - Stephen King"
    ],
    ("I"): [
        "Bumi Manusia - Pramoedya Ananta Toer",
        "Anak Semua Bangsa - Pramoedya Ananta Toer",
        "Jejak Langkah - Pramoedya Ananta Toer",
        "Gadis Kretek - Ratih Kumala",
        "Keluarga Gerilya - Pramoedya Ananta Toer",
        "Hikayat Orang Linglung - Pramoedya Ananta Toer",
        "Perempuan Kembang Jepun - Remy Sylado",
        "Surat Kecil untuk Tuhan - Agnes Davonar",
        "Sang Pangeran - Niccolo Machiavelli",
        "Sejarah Dunia yang Disembunyikan - Jonathan Black"
        "Negara Kelima - E.S. Ito",
        "Pulau Buru - Pramoedya Ananta Toer",
        "Guru Aini - Andrea Hirata",
        "Burung-burung Manyar - Y.B. Mangunwijaya",
        "Laskar Pelangi - Andrea Hirata",
        "Amba - Laksmi Pamuntjak",
        "Lelaki Harimau - Eka Kurniawan",
        "Cantik Itu Luka - Eka Kurniawan",
        "Orang-Orang Bloomington - Budi Darma",
        "Tenggelamnya Kapal Van Der Wijck - Hamka",
        "Di Bawah Lindungan Ka'bah - Hamka",
        "Max Havelaar - Multatuli",
        "Ronggeng Dukuh Paruk - Ahmad Tohari",
        "Bekisar Merah - Ahmad Tohari",
        "Gadis Pantai - Pramoedya Ananta Toer",
        "Sang Pemimpi - Andrea Hirata",
        "Ayahku (Bukan) Pembohong - Tere Liye",
        "Pulang - Leila S. Chudori",
        "Laut Bercerita - Leila S. Chudori",
        "Cinta di Dalam Gelas - Andrea Hirata",
        "Rahasia Meede - E.S. Ito",
        "Melawan Takdir - Hamka",
        "Pergolakan Pemikiran Islam - Nurcholish Madjid",
        "Api Sejarah - Ahmad Mansur Suryanegara",
        "Tan Malaka: Gerakan Kiri dan Revolusi Indonesia - Harry Poeze",
        "Muhammad Al-Fatih 1453 - Felix Siauw",
        "Dari Penjara ke Penjara - Tan Malaka",
        "Revolusi Belum Selesai - Tan Malaka",
        "Madilog - Tan Malaka",
        "Aku, Anak PKI - Hersri Setiawan",
        "Cerita dari Blora - Pramoedya Ananta Toer",
        "Sang Alkemis - Paulo Coelho",
        "Kronik Revolusi Indonesia - Anhar Gonggong",
        "Sejarah Perang Diponegoro - Peter Carey",
        "Biografi Soekarno - Cindy Adams",
        "Runtuhnya Kerajaan Hindu-Jawa - Slamet Muljana",
        "Sejarah Perempuan Indonesia - Toer Haris",
        "Menolak Punah - Bondan Winarno",
        "G 30 S - Eros Djarot",
        "Sebuah Seni untuk Bersikap Bodo Amat - Mark Manson",
        "Sapiens: A Brief History of Humankind - Yuval Noah Harari",
        "Homo Deus: A Brief History of Tomorrow - Yuval Noah Harari",
        "The Silk Roads: A New History of the World - Peter Frankopan",
        "Guns, Germs, and Steel - Jared Diamond",
        "The Rise and Fall of the Third Reich - William Shirer",
        "1776 - David McCullough",
        "A People's History of the United States - Howard Zinn",
        "The Diary of a Young Girl - Anne Frank",
        "Night - Elie Wiesel",
        "The Second World War - Antony Beevor",
        "The Cold War: A New History - John Lewis Gaddis",
        "The Wright Brothers - David McCullough",
        "Team of Rivals - Doris Kearns Goodwin",
        "The Guns of August - Barbara W. Tuchman",
        "The Splendid and the Vile - Erik Larson",
        "1491: New Revelations of the Americas Before Columbus - Charles C. Mann",
        "The Plantagenets - Dan Jones",
        "The Templars: The Rise and Spectacular Fall of God’s Holy Warriors - Dan Jones",
        "A Short History of Nearly Everything - Bill Bryson",
        "The Crusades - Thomas Asbridge",
        "The Fall of Constantinople 1453 - Steven Runciman",
        "SPQR: A History of Ancient Rome - Mary Beard",
        "The Histories - Herodotus",
        "The Peloponnesian War - Thucydides",
        "Alexander the Great - Philip Freeman",
        "Genghis Khan and the Making of the Modern World - Jack Weatherford",
        "The Ottoman Empire - Jason Goodwin",
        "The Making of the Atomic Bomb - Richard Rhodes",
        "Postwar: A History of Europe Since 1945 - Tony Judt",
        "The Crusades Through Arab Eyes - Amin Maalouf",
        "Battle Cry of Freedom - James McPherson",
        "Napoleon: A Life - Andrew Roberts",
        "Stalingrad: The Fateful Siege - Antony Beevor",
        "The Great War and Modern Memory - Paul Fussell",
        "Mao: The Unknown Story - Jung Chang",
        "The War of the World - Niall Ferguson",
        "The Rise of Theodore Roosevelt - Edmund Morris",
        "The Federalist Papers - Alexander Hamilton, James Madison, John Jay",
        "The Devil in the White City - Erik Larson",
        "Why Nations Fail - Daron Acemoglu and James Robinson",
        "A History of the World in 6 Glasses - Tom Standage",
        "The Professor and the Madman - Simon Winchester",
        "Catherine the Great: Portrait of a Woman - Robert K. Massie",
        "Berlin: The Downfall 1945 - Antony Beevor",
        "The Path Between the Seas - David McCullough",
        "Rubicon: The Last Years of the Roman Republic - Tom Holland",
        "The Map That Changed the World - Simon Winchester",
        "The Romanovs - Simon Sebag Montefiore",
        "The Wright Brothers - David McCullough"
    ],
    ("J"): [
        "Rich Dad Poor Dad - Robert Kiyosaki",
        "The 7 Habits of Highly Effective People - Stephen Covey",
        "How to Win Friends and Influence People - Dale Carnegie",
        "Atomic Habits - James Clear",
        "Mindset: The New Psychology of Success - Carol Dweck",
        "The Power of Now - Eckhart Tolle",
        "Seni Hidup Minimalis - Francine Jay",
        "Buku Latihan Bersyukur - Henry Manampiring",
        "Hidup Sederhana - Desi Anwar",
        "Dare to Lead - Brené Brown"
        "Berani Tidak Disukai - Ichiro Kishimi & Fumitake Koga",
        "Filosofi Teras - Henry Manampiring",
        "Sebuah Seni Untuk Bersikap Bodo Amat - Mark Manson (edisi Indonesia)",
        "Merawat Luka Batin - Ratih Ibrahim",
        "Mindset Positif - James Anderson (terjemahan)",
        "Psikologi Kepribadian - Hurlock",
        "Manajemen Waktu - Brian Tracy (edisi Indonesia)",
        "Kekuatan Pikiran Bawah Sadar - Joseph Murphy (terjemahan)",
        "Jangan Membuat Masalah Kecil Jadi Besar - Richard Carlson (Indonesia)",
        "Buku Pintar Kepribadian - Arief Hidayat",
        "Zero to One - Peter Thiel (Indonesia)",
        "Melawan Stres Dengan Self-Love - Elizabeth T. Santosa",
        "Berproses Menjadi Manusia - Alvi Syahrin",
        "Mencari Makna Hidup - Victor Frankl (Indonesia)",
        "Mindfulness Untuk Pemula - Thich Nhat Hanh",
        "Hidup Bahagia Ala Stoikisme - William B. Irvine (Indonesia)",
        "Meraih Sukses Dengan Visualisasi - Andri Novanto",
        "Catatan Juang - Fiersa Besari",
        "Buka Mata, Buka Hati - Ahmad Rifa'i Rif'an",
        "Menang Tanpa Menindas - Muhammad Iqbal",
        "Kekuatan Disiplin Diri - John Maxwell (Indonesia)",
        "Kisah Hidup Para Tokoh Sukses - Dian Sastro",
        "Jalan Sunyi Seorang Penulis - Tere Liye",
        "Resep Sederhana Untuk Hidup Bahagia - Ajahn Brahm",
        "Self-Healing, Self-Love - Dewi Nur Aisyah",
        "Ruang Tengah Kehidupan - Desi Anwar",
        "Cinta Dalam 99 Nama-Mu - A. Fuadi",
        "Mindset Juara - Rene Suhardono",
        "Anatomi Rasa Takut - Yuswohady",
        "Hidup Sesuai Nilai Diri - Ika Natassa",
        "Tantangan Hidup & Harapan Baru - Andrie Wongso",
        "Dunia Tak Selebar Daun Kelor - Andrie F. Kusuma",
        "Melangkah Dengan Tujuan - Linda Agustiani",
        "Emotional Detox - E. Lestari",
        "Setiap Orang Bisa Sukses - Anwar Sudrajat",
        "Makna Sukses Sejati - Arman Maulana",
        "Melatih Fokus & Konsentrasi - Rahmad Sudiro",
        "Catatan Sederhana Tentang Kehidupan - Fitri Yani",
        "Mengenal Diri Lebih Dalam - Ahmad Taufiq",
        "Percaya Proses Hidup - Dian Suryadi",
        "Think and Grow Rich - Napoleon Hill",
        "You Are a Badass - Jen Sincero",
        "Deep Work - Cal Newport",
        "The Subtle Art of Not Giving a F*ck - Mark Manson",
        "Make Your Bed - William H. McRaven",
        "The 48 Laws of Power - Robert Greene",
        "Outliers: The Story of Success - Malcolm Gladwell",
        "Grit: The Power of Passion and Perseverance - Angela Duckworth",
        "12 Rules for Life - Jordan B. Peterson",
        "Daring Greatly - Brené Brown",
        "Start With Why - Simon Sinek",
        "Drive: The Surprising Truth About Motivation - Daniel H. Pink",
        "Tools of Titans - Tim Ferriss",
        "Man's Search for Meaning - Viktor E. Frankl",
        "The Happiness Project - Gretchen Rubin",
        "The Gifts of Imperfection - Brené Brown",
        "Essentialism: The Disciplined Pursuit of Less - Greg McKeown",
        "Digital Minimalism - Cal Newport",
        "Eat That Frog! - Brian Tracy",
        "Awaken the Giant Within - Tony Robbins",
        "The Magic of Thinking Big - David J. Schwartz",
        "Unlimited Power - Tony Robbins",
        "Principles: Life and Work - Ray Dalio",
        "High Performance Habits - Brendon Burchard",
        "The Compound Effect - Darren Hardy",
        "Big Potential - Shawn Achor",
        "No Excuses! - Brian Tracy",
        "Mindfulness in Plain English - Bhante Gunaratana",
        "Emotional Intelligence - Daniel Goleman",
        "Tiny Habits - BJ Fogg",
        "The Four Agreements - Don Miguel Ruiz",
        "The War of Art - Steven Pressfield",
        "So Good They Can't Ignore You - Cal Newport",
        "Who Moved My Cheese? - Spencer Johnson",
        "Failing Forward - John C. Maxwell",
        "The Success Principles - Jack Canfield",
        "The Art of Happiness - Dalai Lama",
        "Mindset Makeover - Carol Dweck",
        "The Millionaire Fastlane - MJ DeMarco",
        "Can't Hurt Me - David Goggins",
        "The Slight Edge - Jeff Olson",
        "Your Best Year Ever - Michael Hyatt",
        "The Miracle Morning - Hal Elrod",
        "How Successful People Think - John C. Maxwell",
        "The Power of Habit - Charles Duhigg",
        "Lean In - Sheryl Sandberg",
        "Rising Strong - Brené Brown",
        "What I Know For Sure - Oprah Winfrey",
        "The Alchemist - Paulo Coelho",
        "The One Thing - Gary Keller",
        "Find Your Why - Simon Sinek"
    ]
}


def tampilkan_genre():
    print("\nGENRE BUKU:")
    print("A. Fiksi")
    print("B. Non-Fiksi")
    print("C. Fiksi Ilmiah (Science Fiction)")
    print("D. Fantasi")
    print("E. Romansa")
    print("F. Misteri/Detektif")
    print("G. Thriller/Suspense")
    print("H. Horror")
    print("I. Sejarah (Historical)")
    print("J. Pengembangan Diri (Self-Help)")

buku_tereliminasi = {}

while True:
    print("\n----- SISTEM REKOMENDASI BUKU PERPUSTAKAAN -----\n")
    time.sleep(2)
    nama = input("Masukkan nama Anda: ")
    print(f"Halo {nama}, Selamat datang!.")
    time.sleep(2)

    while True:
        tampilkan_genre()
        print()
        genre_dipilih = input("Masukkan kode genre yang Anda minati: ").upper()

        if genre_dipilih not in dataset_buku:
            print("\nMaaf, genre tidak tersedia. Silakan pilih kode genre lain.\n")
            time.sleep(1)
            continue

        if genre_dipilih not in buku_tereliminasi:
            buku_tereliminasi[genre_dipilih] = set()
        buku_tersedia = [buku for buku in dataset_buku[genre_dipilih] if buku not in buku_tereliminasi[genre_dipilih]]

        if not buku_tersedia:
            print("\nSemua buku pada genre ini telah direkomendasikan.\n")
            ulangi = input("Ingin memilih genre lain? (ya/tidak): ").upper()
            if ulangi == "tidak":
                break
            elif ulangi != "ya":
                print()
                print("Kode tidak valid, silakan masukkan 'ya' atau 'tidak'.")
                print()
                continue
            continue

        while True:
            jumlah_buku = input("\nBerapa jumlah buku yang ingin direkomendasikan? ")
            if not jumlah_buku.isdigit() or int(jumlah_buku) <= 0:
                print("\nMasukkan jumlah buku yang valid!")
                time.sleep(1)
                continue
            
            jumlah_buku = int(jumlah_buku)
            rekomendasi = random.sample(buku_tersedia, min(jumlah_buku, len(buku_tersedia)))

            print("\nRekomendasi buku untuk Anda:")
            for buku in rekomendasi:
                print(f"- {buku}")
                buku_tereliminasi[genre_dipilih].add(buku)

            buku_tersedia = [buku for buku in dataset_buku[genre_dipilih] if buku not in buku_tereliminasi[genre_dipilih]]
            if not buku_tersedia:
                print("\nMaaf, jumlah maksimal buku yang ada hanya 100.")
                print("Semua buku pada genre ini telah direkomendasikan.")
                break

            while True:
                ulangi_genre = input("\nIngin rekomendasi buku lagi untuk genre ini? (ya/tidak): ").lower()
                if ulangi_genre == "tidak":
                    break
                elif ulangi_genre == "ya":
                    break
                else:
                    print()
                    print("Kode tidak valid, silakan masukkan 'ya' atau 'tidak'.")
                    print()

            if ulangi_genre == "tidak":
                break


        while True:
            ulangi = input("\nIngin rekomendasi buku untuk genre lain? (ya/tidak): ").lower()
            if ulangi == "tidak":
                break
            elif ulangi == "ya":
                break
            else:
                print()
                print("Kode tidak valid, silakan masukkan 'ya' atau 'tidak'.")
                print()
        
        if ulangi == "tidak":
            break

    print("\nTerima kasih telah menggunakan sistem kami!")
    time.sleep(5)
    print("\nMemulai sistem kembali... \n******************************************************************************************************************************************************************************************************************************\n\n")